kind: GCPTrafficExtension
apiVersion: networking.gke.io/v1
metadata:
  name: model-armor-tutorial-gcp-traffic-extension
  namespace: default
spec:
  targetRefs:
  - group: "gateway.networking.k8s.io"
    kind: Gateway
    name: model-armor-tutorial-gateway
  extensionChains:
  - name: model-armor-chain
    matchCondition:
      celExpressions:
      - celMatcher: 'request.path == "/v1/completions"'
    extensions:
    - name: model-armor-service
      supportedEvents:
      - RequestHeaders
      - RequestBody
      - ResponseBody
      - ResponseHeaders
      - ResponseTrailers
      - RequestTrailers
      timeout: "10000ms"
      googleAPIServiceName: "modelarmor.us-central1.rep.googleapis.com"
      failOpen: false
      metadata:
        model_armor_settings: '[{"model":"food-review-im","model_response_template_id":"projects/akvelon-gke-aieco/locations/us-central1/templates/model-armor-tutorial-default-template","user_prompt_template_id":"projects/akvelon-gke-aieco/locations/us-central1/templates/model-armor-tutorial-default-template"},{"model":"meta-llama/Llama-3.1-8B-Instruct","model_response_template_id":"projects/akvelon-gke-aieco/locations/us-central1/templates/model-armor-tutorial-default-template","user_prompt_template_id":"projects/akvelon-gke-aieco/locations/us-central1/templates/model-armor-tutorial-default-template"}]'
