apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-dws-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "gpu-t4-dws"
spec:
  nodeLabels:
    cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "cloud.google.com/gke-queued"
      operator: "Exists"
      effect: "NoSchedule"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: sample-dws-multikueue
spec:
  controllerName: kueue.x-k8s.io/multikueue
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: MultiKueueConfig
    name: multikueue-dws
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: MultiKueueConfig
metadata:
  name: multikueue-dws
spec:
  clusters:
    - multikueue-dws-worker-asia
    - multikueue-dws-worker-us
    - multikueue-dws-worker-eu
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: MultiKueueCluster
metadata:
  name: multikueue-dws-worker-asia
spec:
  kubeConfig:
    locationType: Secret
    location: worker-asia-southeast1-secret

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: MultiKueueCluster
metadata:
  name: multikueue-dws-worker-eu
spec:
  kubeConfig:
    locationType: Secret
    location: worker-europe-west4-secret
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: MultiKueueCluster
metadata:
  name: multikueue-dws-worker-us
spec:
  kubeConfig:
    locationType: Secret
    location: worker-us-east4-secret

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: MultiKueueCluster
metadata:
  name: multikueue-dws-worker-asia
spec:
  kubeConfig:
    locationType: Secret
    location: worker-asia-southeast1-secret

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "dws-cluster-queue"
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage"]
      flavors:
        - name: "default-dws-flavor"
          resources:
            - name: "cpu"
              nominalQuota: 10000 # Infinite quota.
            - name: "memory"
              nominalQuota: 10000Gi # Infinite quota.
            - name: "ephemeral-storage"
              nominalQuota: 10000Gi # Infinite quota.
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "gpu-t4-dws"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 10
  admissionChecks:
    - sample-dws-multikueue
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "dws-local-queue"
spec:
  clusterQueue: "dws-cluster-queue"
---

