apiVersion: batch/v1
kind: Job
metadata:
  generateName: dws-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: dws-local-queue
  annotations:
    provreq.kueue.x-k8s.io/maxRunDurationSeconds: "600"
spec:
  ttlSecondsAfterFinished: 3600
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
        - name: dummy-job
          image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
          args: ["120s"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
              ephemeral-storage: "0Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
              ephemeral-storage: "0Mi"

      restartPolicy: Never
