steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/llama-ray/adk-agent:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/llama-ray/adk-agent:latest']
images:
- 'us-docker.pkg.dev/$PROJECT_ID/llama-ray/adk-agent:latest'