apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-llama-guard-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-guard-3-server
  template:
    metadata:
      labels:
        app: llama-guard-3-server
        ai.gke.io/model: llama-guard-3-8b
        ai.gke.io/inference-server: vllm
        examples.ai.gke.io/source: user-guide
    spec:
      containers:
      - name: inference-server
        image: vllm/vllm-openai:v0.8.5
        resources:
          requests:
            cpu: "2"
            memory: "10Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "2"
            memory: "10Gi"
            nvidia.com/gpu: "1"
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
        args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=1
        - --host=0.0.0.0
        - --port=8000
        - --trust-remote-code # new arguments
        - --enable-chunked-prefill
        - --max-model-len=32768
        env:
        - name: MODEL_ID
          value: meta-llama/Llama-Guard-3-8B
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /templates
          name: chat-templates
          readOnly: true
      volumes:
      - name: chat-templates
        configMap:
          name: llama-chat-templates
      - name: dshm
        emptyDir:
            medium: Memory
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-llama-guard-3-service
spec:
  selector:
    app: llama-guard-3-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
